# Generated by Django 5.1 on 2024-08-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='Teacher',
        ),
    ]
