# Generated by Django 5.0.7 on 2024-08-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
